[package]
name = "j2me_emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
classfile-parser = "0.3.8"
egui-wgpu = "0.34.2"
egui-winit = "0.34.2"
image = "0.25.10"
parking_lot = { version = "0.12.5", features = ["deadlock_detection"] }
pixels = "0.17.1"
zip = "8.6.0"


[profile.dev]
panic = "abort"
